# Python unit tests
name: Python

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python-dev libldap2-dev libsasl2-dev libssl-dev
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: black
        run: black --check setup.py flask_appbuilder
      - name: flake8
        run: flake8 flask_appbuilder

  test-postgres:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7]
    env:
      SQLALCHEMY_DATABASE_URI:
        postgresql+psycopg2://pguser:pguserpassword@127.0.0.1:15432/app
    services:
      postgres:
        image: postgres:10-alpine
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pguserpassword
          POSTGRES_DB: app
        ports:
          - 15432:5432
        command: postgres -c 'max_connections=500'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python-dev libldap2-dev libsasl2-dev libssl-dev
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          nosetests --stop -v --with-coverage --cover-package=flask_appbuilder flask_appbuilder.tests --ignore-files="test_mongoengine\.py"
      - name: Upload code coverage
        run: |
          bash <(curl -s https://codecov.io/bash) -cF python
