# Python unit tests
name: Python

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requitements-dev.txt
      - name: black
        run: black flask_appbuilder
      - name: flake8
        run: flake8 flask_appbuilder
